-- MySQL Script generated by MySQL Workbench
-- Sat 22 Oct 2022 04:01:00 PM -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sinmbas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sinmbas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sinmbas` ;
USE `sinmbas` ;

-- -----------------------------------------------------
-- Table `sinmbas`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinmbas`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` TINYINT NOT NULL,
  `icard` INT(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `icard_UNIQUE` (`icard` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinmbas`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinmbas`.`Proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `info` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinmbas`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinmbas`.`Categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `info` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinmbas`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinmbas`.`Productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `stock` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `info` TEXT NULL,
  `Categorias_id` INT NOT NULL,
  `Proveedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Categorias_idx` (`Categorias_id` ASC) ,
  INDEX `Proveedores_idx` (`Proveedores_id` ASC) ,
  CONSTRAINT `Categoria`
    FOREIGN KEY (`Categorias_id`)
    REFERENCES `sinmbas`.`Categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Proveedor`
    FOREIGN KEY (`Proveedores_id`)
    REFERENCES `sinmbas`.`Proveedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinmbas`.`Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinmbas`.`Pagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `code` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinmbas`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinmbas`.`Ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `total` FLOAT NOT NULL,
  `Pagos_id` INT NOT NULL,
  `Cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Pagos_idx` (`Pagos_id` ASC) ,
  INDEX `Cliente_idx` (`Cliente_id` ASC) ,
  CONSTRAINT `Pagos`
    FOREIGN KEY (`Pagos_id`)
    REFERENCES `sinmbas`.`Pagos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cliente`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `sinmbas`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinmbas`.`DetalleVentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinmbas`.`DetalleVentas` (
  `amount` INT NOT NULL,
  `Productos_id` INT NOT NULL,
  `Ventas_id` INT NOT NULL,
  INDEX `Productos_idx` (`Productos_id` ASC) ,
  INDEX `Ventas_idx` (`Ventas_id` ASC) ,
  CONSTRAINT `Productos`
    FOREIGN KEY (`Productos_id`)
    REFERENCES `sinmbas`.`Productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Ventas`
    FOREIGN KEY (`Ventas_id`)
    REFERENCES `sinmbas`.`Ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinmbas`.`Facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinmbas`.`Facturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Ventas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Ventas_idx` (`Ventas_id` ASC) ,
  CONSTRAINT `Ventas2`
    FOREIGN KEY (`Ventas_id`)
    REFERENCES `sinmbas`.`Ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sinmbas`.`Envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sinmbas`.`Envios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `state` TINYINT NOT NULL DEFAULT 0,
  `date_send` DATETIME NULL,
  `date_recd` DATETIME NULL,
  `Factura_id` INT NOT NULL,
  `Trabajador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Factura_idx` (`Factura_id` ASC) ,
  INDEX `Trabajador_idx` (`Trabajador_id` ASC) ,
  CONSTRAINT `Factura`
    FOREIGN KEY (`Factura_id`)
    REFERENCES `sinmbas`.`Facturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Trabajador`
    FOREIGN KEY (`Trabajador_id`)
    REFERENCES `sinmbas`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
