insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (1, 'Wine - Balbach Riverside', 198, 6435, 'turpis donec posuere metus', 7, 22);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (2, 'Sauce Tomato Pouch', 219, 8441, 'ridiculus mus etiam vel', 8, 38);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (3, 'Bar Mix - Pina Colada, 355 Ml', 163, 4161, 'in purus eu magna', 5, 17);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (4, 'Wine - Shiraz South Eastern', 168, 7525, 'amet eleifend pede', 1, 12);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (5, 'Ice Cream - Life Savers', 157, 12831, 'volutpat sapien arcu sed', 1, 46);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (6, 'Soup - Knorr, Chicken Gumbo', 208, 6745, 'sit amet eleifend', 8, 16);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (7, 'Tandoori Curry Paste', 135, 11406, 'quis augue luctus', 3, 27);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (8, 'Veal - Inside Round / Top, Lean', 130, 3472, 'vulputate elementum nullam varius nulla', 4, 17);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (9, 'Cranberries - Dry', 159, 10355, 'ullamcorper augue a', 2, 12);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (10, 'Ecolab Crystal Fusion', 154, 1654, 'eget elit sodales scelerisque mauris', 7, 48);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (11, 'Dish Towel', 140, 14379, 'nulla mollis molestie', 4, 6);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (12, 'Syrup - Kahlua Chocolate', 155, 13462, 'ante ipsum primis in faucibus', 7, 25);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (13, 'Uniform Linen Charge', 211, 6812, 'pellentesque volutpat dui', 4, 40);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (14, 'Sauce - Hoisin', 110, 14005, 'ante vel ipsum praesent', 8, 23);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (15, 'Wine - Saint Emilion Calvet', 223, 8033, 'vestibulum sed magna at nunc', 10, 8);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (16, 'Chicken - Wings, Tip Off', 211, 13065, 'varius ut blandit non', 7, 8);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (17, 'Bagelers - Cinn / Brown', 140, 11401, 'bibendum imperdiet nullam orci', 3, 2);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (18, 'Eggplant - Asian', 139, 7583, 'condimentum neque sapien placerat', 3, 39);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (19, 'Extract - Lemon', 159, 1501, 'duis consequat dui nec nisi', 4, 5);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (20, 'Venison - Liver', 225, 14391, 'vestibulum velit id', 8, 8);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (21, 'Crackers - Soda / Saltins', 110, 5750, 'interdum eu tincidunt in leo', 5, 30);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (22, 'Coconut - Creamed, Pure', 223, 1742, 'eu mi nulla ac enim', 2, 46);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (23, 'Chicken - Whole Fryers', 157, 5559, 'non velit donec diam', 3, 5);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (24, 'Ice Cream Bar - Oreo Sandwich', 164, 5314, 'morbi a ipsum', 3, 32);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (25, 'Fish - Artic Char, Cold Smoked', 128, 10722, 'id ligula suspendisse ornare', 5, 36);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (26, 'Cheese - Provolone', 220, 9339, 'potenti nullam porttitor lacus at', 4, 26);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (27, 'Cake - Cheese Cake 9 Inch', 139, 8672, 'augue a suscipit', 2, 29);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (28, 'Mushroom - Porcini Frozen', 225, 12519, 'mauris morbi non', 10, 37);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (29, 'Paper Cocktail Umberlla 80 - 180', 169, 9128, 'id sapien in sapien iaculis', 4, 41);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (30, 'Spice - Peppercorn Melange', 179, 11460, 'integer aliquet massa id', 7, 21);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (31, 'Rice - Brown', 126, 4593, 'eget elit sodales scelerisque mauris', 4, 15);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (32, 'Shrimp - Baby, Warm Water', 160, 13531, 'ac lobortis vel dapibus at', 2, 43);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (33, 'Beer - Pilsner Urquell', 176, 8939, 'libero nullam sit', 3, 5);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (34, 'Pepper - Roasted Red', 246, 14824, 'at dolor quis', 3, 9);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (35, 'Island Oasis - Ice Cream Mix', 216, 9796, 'interdum mauris ullamcorper purus', 9, 48);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (36, 'English Muffin', 136, 4821, 'mauris eget massa', 7, 49);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (37, 'Cocoa Powder - Natural', 196, 5382, 'odio consequat varius', 10, 20);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (38, 'Chips - Miss Vickies', 91, 1960, 'nec euismod scelerisque quam', 1, 33);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (39, 'Trueblue - Blueberry', 242, 8344, 'nam nulla integer', 10, 28);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (40, 'Cookie Dough - Chocolate Chip', 173, 3330, 'mauris sit amet eros suspendisse', 9, 30);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (41, 'Pepper - Green Thai', 136, 12153, 'sed lacus morbi', 8, 37);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (42, 'Lettuce - Iceberg', 218, 13815, 'velit nec nisi', 5, 48);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (43, 'Beef - Rouladin, Sliced', 150, 11784, 'et eros vestibulum', 2, 4);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (44, 'Soup - Campbells, Chix Gumbo', 221, 2576, 'non mauris morbi non lectus', 4, 10);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (45, 'Food Colouring - Blue', 155, 13706, 'dictumst morbi vestibulum velit', 10, 16);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (46, 'Liqueur Banana, Ramazzotti', 238, 3446, 'vivamus in felis eu', 4, 31);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (47, 'Kippers - Smoked', 226, 14961, 'sapien urna pretium nisl', 5, 38);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (48, 'Madeira', 230, 5124, 'morbi sem mauris', 9, 15);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (49, 'Wood Chips - Regular', 234, 4178, 'nullam orci pede venenatis', 10, 19);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (50, 'Jam - Marmalade, Orange', 220, 9647, 'ac consequat metus sapien', 7, 16);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (51, 'Wine - Two Oceans Cabernet', 110, 10339, 'curae duis faucibus accumsan odio', 3, 47);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (52, 'Rice Paper', 226, 9570, 'lacinia nisi venenatis tristique', 4, 22);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (53, 'Carbonated Water - Wildberry', 198, 4143, 'dignissim vestibulum vestibulum ante', 9, 38);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (54, 'Lobster - Tail 6 Oz', 219, 8375, 'sit amet justo morbi', 9, 48);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (55, 'Wakami Seaweed', 215, 7721, 'lorem quisque ut erat curabitur', 6, 10);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (56, 'Bread - White, Unsliced', 138, 3526, 'sociis natoque penatibus et magnis', 9, 7);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (57, 'Orange - Blood', 120, 7690, 'at velit eu est', 3, 26);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (58, 'Bread - Malt', 164, 14666, 'ante ipsum primis', 4, 40);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (59, 'Wine - White, Ej Gallo', 139, 8155, 'mauris non ligula pellentesque', 8, 32);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (60, 'Turkey Tenderloin Frozen', 222, 10129, 'augue quam sollicitudin vitae consectetuer', 1, 30);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (61, 'Bols Melon Liqueur', 154, 10229, 'id mauris vulputate elementum nullam', 10, 49);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (62, 'Table Cloth 62x114 White', 228, 3686, 'quis libero nullam', 10, 16);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (63, 'Parsnip', 153, 9968, 'erat tortor sollicitudin mi sit', 4, 35);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (64, 'Hersey Shakes', 234, 9140, 'lacinia sapien quis', 8, 17);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (65, 'Halibut - Whole, Fresh', 246, 5004, 'at velit vivamus vel', 5, 19);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (66, 'Olives - Stuffed', 232, 11538, 'vel lectus in quam fringilla', 7, 50);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (67, 'Spinach - Packaged', 170, 1563, 'eleifend quam a', 3, 1);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (68, 'Loquat', 129, 1360, 'vulputate elementum nullam varius nulla', 5, 31);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (69, 'Lobster - Baby, Boiled', 179, 11985, 'quisque arcu libero rutrum ac', 10, 36);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (70, 'Nutmeg - Ground', 148, 4535, 'duis bibendum morbi', 5, 48);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (71, 'Scrubbie - Scotchbrite Hand Pad', 181, 3804, 'dis parturient montes', 10, 7);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (72, 'Honey - Lavender', 235, 4947, 'turpis donec posuere metus', 5, 1);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (73, 'Cookie Choc', 249, 3682, 'pharetra magna vestibulum aliquet', 10, 14);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (74, 'Lid - 10,12,16 Oz', 158, 14057, 'diam vitae quam suspendisse', 6, 45);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (75, 'Mushroom - Shitake, Dry', 105, 12904, 'in hac habitasse platea dictumst', 1, 38);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (76, 'Pasta - Lasagna Noodle, Frozen', 209, 5949, 'auctor sed tristique in', 7, 47);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (77, 'Chips - Potato Jalapeno', 225, 11832, 'hac habitasse platea dictumst morbi', 3, 50);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (78, 'Beer - Rickards Red', 186, 14777, 'amet nulla quisque arcu', 8, 45);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (79, 'Tea - Lemon Scented', 116, 10945, 'mi integer ac neque duis', 1, 35);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (80, 'Veal - Brisket, Provimi, Bone - In', 100, 12851, 'ultrices posuere cubilia', 6, 12);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (81, 'Steel Wool S.o.s', 105, 11122, 'est quam pharetra', 6, 19);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (82, 'Pate Pans Yellow', 94, 9838, 'nulla integer pede justo', 6, 38);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (83, 'Cookie Choc', 133, 13578, 'arcu sed augue aliquam', 3, 31);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (84, 'Tea - English Breakfast', 191, 13230, 'nulla neque libero', 4, 50);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (85, 'Chips - Assorted', 144, 9909, 'nulla facilisi cras non', 10, 25);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (86, 'Bamboo Shoots - Sliced', 128, 12221, 'nulla suscipit ligula in', 8, 5);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (87, 'Squash - Sunburst', 190, 12704, 'luctus et ultrices', 7, 37);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (88, 'Ocean Spray - Kiwi Strawberry', 135, 14729, 'faucibus orci luctus', 6, 30);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (89, 'Wine - Manischewitz Concord', 205, 10438, 'dui vel sem sed sagittis', 3, 24);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (90, 'Tomato - Peeled Italian Canned', 120, 4124, 'mauris non ligula pellentesque', 3, 21);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (91, 'Juice - Tomato, 10 Oz', 91, 5210, 'est risus auctor sed tristique', 4, 6);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (92, 'Flour - Semolina', 216, 13118, 'sed lacus morbi', 2, 1);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (93, 'Grenadillo', 95, 2608, 'nulla ut erat', 6, 17);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (94, 'Beer - Pilsner Urquell', 222, 7497, 'consectetuer eget rutrum at lorem', 2, 48);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (95, 'Beans - Turtle, Black, Dry', 192, 3547, 'hac habitasse platea dictumst', 3, 26);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (96, 'Bread - Roll, Whole Wheat', 200, 1620, 'at feugiat non pretium quis', 6, 11);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (97, 'Pasta - Lasagna Noodle, Frozen', 184, 8683, 'in lacus curabitur at', 9, 40);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (98, 'Sultanas', 95, 4361, 'mollis molestie lorem quisque ut', 1, 26);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (99, 'Wine - Cousino Macul Antiguas', 211, 10512, 'enim in tempor turpis nec', 10, 35);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (100, 'Wine - Montecillo Rioja Crianza', 220, 8441, 'venenatis lacinia aenean sit amet', 10, 25);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (101, 'Butter - Salted', 223, 5927, 'sollicitudin mi sit', 2, 39);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (102, 'Wine - Cousino Macul Antiguas', 171, 2551, 'vestibulum ac est', 1, 6);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (103, 'Mcguinness - Blue Curacao', 238, 14245, 'eu magna vulputate luctus', 8, 44);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (104, 'Tea - Herbal I Love Lemon', 90, 7157, 'est congue elementum', 9, 43);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (105, 'Beans - Yellow', 93, 14742, 'erat eros viverra', 10, 19);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (106, 'Herb Du Provence - Primerba', 162, 5514, 'ante ipsum primis in faucibus', 8, 23);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (107, 'Bagelers - Cinn / Brown Sugar', 139, 8272, 'sit amet consectetuer', 2, 13);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (108, 'Oil - Pumpkinseed', 228, 10369, 'eu est congue elementum', 7, 7);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (109, 'Frangelico', 142, 2391, 'suspendisse potenti nullam', 6, 38);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (110, 'Basil - Seedlings Cookstown', 218, 8419, 'sapien placerat ante nulla', 9, 29);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (111, 'Lemon Balm - Fresh', 131, 4411, 'libero ut massa', 4, 44);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (112, 'Carbonated Water - Strawberry', 112, 5249, 'porta volutpat quam', 2, 17);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (113, 'Compound - Mocha', 97, 11402, 'morbi quis tortor', 1, 19);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (114, 'Cumin - Ground', 109, 8635, 'in quis justo maecenas rhoncus', 5, 21);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (115, 'Lamb - Whole, Fresh', 154, 8941, 'orci mauris lacinia sapien quis', 3, 32);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (116, 'Pepper - Green Thai', 203, 1380, 'non mauris morbi non', 5, 23);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (117, 'Pork - Bones', 176, 6707, 'quisque arcu libero rutrum ac', 7, 16);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (118, 'Yeast Dry - Fermipan', 137, 10347, 'id mauris vulputate', 10, 13);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (119, 'Flavouring - Raspberry', 150, 2489, 'dictumst morbi vestibulum velit', 9, 11);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (120, 'Appetizer - Cheese Bites', 106, 6877, 'diam cras pellentesque volutpat dui', 4, 17);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (121, 'Soup - Campbells Asian Noodle', 173, 2832, 'tellus nisi eu orci', 7, 43);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (122, 'Wine - Chablis 2003 Champs', 168, 2879, 'ligula pellentesque ultrices', 4, 1);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (123, 'Turkey Tenderloin Frozen', 117, 12755, 'nisi eu orci mauris', 9, 4);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (124, 'Beef - Short Ribs', 161, 3460, 'in porttitor pede justo', 6, 5);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (125, 'Energy Drink - Franks Original', 212, 4621, 'non quam nec dui luctus', 9, 5);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (126, 'Cake - Lemon Chiffon', 246, 4336, 'ac diam cras pellentesque volutpat', 1, 40);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (127, 'Basil - Thai', 166, 11474, 'est quam pharetra magna ac', 6, 25);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (128, 'Oil - Olive', 237, 7541, 'rutrum rutrum neque aenean auctor', 9, 27);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (129, 'Rootbeer', 178, 14824, 'consequat morbi a ipsum', 8, 47);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (130, 'Table Cloth 62x120 White', 186, 10704, 'ultrices posuere cubilia curae duis', 8, 31);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (131, 'Tea - Lemon Scented', 189, 5824, 'odio odio elementum', 5, 20);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (132, 'Crackers - Melba Toast', 110, 1100, 'vestibulum proin eu', 5, 11);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (133, 'Cheese - Provolone', 246, 11660, 'ac est lacinia nisi', 6, 3);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (134, 'Bacardi Limon', 98, 12359, 'curabitur gravida nisi at nibh', 7, 36);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (135, 'Glove - Cutting', 219, 6724, 'eget massa tempor', 8, 25);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (136, 'Bar - Sweet And Salty Chocolate', 187, 3305, 'id nulla ultrices aliquet', 4, 47);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (137, 'Muffin - Mix - Creme Brule 15l', 109, 10845, 'eu est congue elementum', 10, 27);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (138, 'Potatoes - Purple, Organic', 234, 10731, 'mauris morbi non lectus aliquam', 8, 15);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (139, 'Island Oasis - Banana Daiquiri', 146, 14953, 'id nulla ultrices aliquet', 10, 28);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (140, 'Soup - French Can Pea', 132, 9341, 'sapien sapien non mi integer', 5, 29);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (141, 'Wine - Red, Colio Cabernet', 115, 4390, 'habitasse platea dictumst maecenas ut', 7, 18);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (142, 'Higashimaru Usukuchi Soy', 163, 4223, 'consequat ut nulla sed accumsan', 9, 22);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (143, 'Wine - Trimbach Pinot Blanc', 249, 1165, 'sit amet cursus id turpis', 9, 8);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (144, 'Beans - Fava, Canned', 136, 13853, 'sed vestibulum sit amet cursus', 2, 11);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (145, 'Poppy Seed', 163, 4317, 'velit vivamus vel', 9, 10);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (146, 'Syrup - Kahlua Chocolate', 155, 11224, 'duis mattis egestas metus', 9, 22);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (147, 'Liners - Baking Cups', 150, 6504, 'orci luctus et', 10, 11);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (148, 'Cheese - Cheddar, Mild', 209, 2301, 'in faucibus orci luctus', 2, 40);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (149, 'Apple - Macintosh', 231, 12970, 'pede malesuada in imperdiet', 4, 43);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (150, 'Ecolab - Orange Frc, Cleaner', 211, 4115, 'sollicitudin vitae consectetuer eget', 6, 33);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (151, 'Spic And Span All Purpose', 182, 6989, 'pede justo eu', 5, 15);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (152, 'Sauce - Balsamic Viniagrette', 159, 7728, 'sagittis nam congue', 10, 15);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (153, 'Pea - Snow', 130, 7539, 'ultrices posuere cubilia curae', 3, 32);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (154, 'Flour - Fast / Rapid', 165, 1253, 'tincidunt in leo maecenas', 9, 13);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (155, 'Puree - Passion Fruit', 219, 8836, 'volutpat dui maecenas tristique est', 2, 33);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (156, 'Chicken - Leg, Fresh', 152, 3638, 'varius ut blandit non interdum', 6, 41);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (157, 'Bread - Sticks, Thin, Plain', 220, 4207, 'justo etiam pretium iaculis', 10, 35);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (158, 'Beef - Top Butt Aaa', 135, 9710, 'interdum mauris ullamcorper purus', 4, 35);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (159, 'Mushroom - Shitake, Dry', 226, 14082, 'cras in purus eu', 9, 22);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (160, 'Cookie Dough - Double', 197, 12970, 'quis lectus suspendisse potenti', 6, 44);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (161, 'Beer - Blue', 190, 9005, 'adipiscing molestie hendrerit', 8, 34);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (162, 'Pasta - Lasagne, Fresh', 189, 6248, 'duis bibendum morbi non quam', 2, 12);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (163, 'Tea - Camomele', 150, 2066, 'dui proin leo odio porttitor', 2, 12);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (164, 'Laundry - Bag Cloth', 91, 11442, 'amet diam in magna', 8, 38);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (165, 'Quinoa', 157, 10565, 'nunc commodo placerat', 7, 40);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (166, 'Sprouts - Pea', 198, 3008, 'dictumst maecenas ut massa', 9, 2);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (167, 'Lemon Grass', 194, 3539, 'dui vel nisl duis ac', 4, 46);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (168, 'Lychee', 165, 14096, 'etiam pretium iaculis justo', 3, 8);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (169, 'Wine - Sauvignon Blanc Oyster', 248, 14802, 'posuere metus vitae', 10, 46);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (170, 'Lobster - Cooked', 240, 5138, 'cum sociis natoque penatibus et', 5, 17);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (171, 'Eggroll', 95, 10209, 'sed vestibulum sit', 3, 28);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (172, 'Eggplant - Regular', 108, 6350, 'sapien varius ut blandit', 5, 9);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (173, 'Yukon Jack', 146, 3874, 'leo odio condimentum id', 4, 6);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (174, 'Pasta - Cannelloni, Sheets, Fresh', 189, 9179, 'cursus vestibulum proin', 4, 25);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (175, 'Garam Marsala', 210, 3162, 'lobortis est phasellus', 8, 9);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (176, 'Chilli Paste, Sambal Oelek', 180, 4327, 'sit amet nulla quisque', 10, 49);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (177, 'Lemon Pepper', 229, 11511, 'nullam varius nulla facilisi', 7, 27);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (178, 'Langers - Ruby Red Grapfruit', 232, 3609, 'amet lobortis sapien', 7, 24);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (179, 'Wine - Guy Sage Touraine', 143, 9349, 'tellus in sagittis', 3, 24);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (180, 'Wine - Jaboulet Cotes Du Rhone', 195, 4869, 'curabitur convallis duis', 2, 17);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (181, 'Island Oasis - Strawberry', 92, 13418, 'primis in faucibus orci', 8, 15);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (182, 'Bread Cranberry Foccacia', 189, 7605, 'in congue etiam', 10, 33);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (183, 'Calypso - Lemonade', 159, 12703, 'sapien cum sociis natoque', 9, 11);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (184, 'Marjoram - Dried, Rubbed', 179, 5002, 'quisque arcu libero rutrum', 4, 35);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (185, 'Bread - Sour Batard', 128, 7778, 'suspendisse potenti nullam porttitor lacus', 3, 37);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (186, 'Sugar - Individual Portions', 132, 9632, 'nunc nisl duis bibendum', 8, 31);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (187, 'Duck - Legs', 247, 7875, 'quisque porta volutpat erat', 5, 26);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (188, 'Island Oasis - Magarita Mix', 245, 9160, 'in tempor turpis nec euismod', 5, 16);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (189, 'Tarts Assorted', 207, 10685, 'tellus nulla ut erat id', 8, 28);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (190, 'Soup - Base Broth Beef', 98, 3509, 'lacus curabitur at ipsum ac', 1, 24);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (191, 'Sword Pick Asst', 90, 5201, 'diam vitae quam', 6, 7);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (192, 'V8 Splash Strawberry Banana', 224, 3073, 'suscipit ligula in lacus', 6, 33);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (193, 'Icecream - Dstk Super Cone', 220, 9474, 'curabitur gravida nisi at', 3, 23);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (194, 'Coconut - Shredded, Sweet', 149, 3301, 'at vulputate vitae nisl', 1, 6);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (195, 'Puff Pastry - Sheets', 153, 4473, 'accumsan odio curabitur convallis', 2, 37);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (196, 'Cheese - Parmesan Grated', 166, 2507, 'pellentesque ultrices phasellus id', 4, 2);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (197, 'Cassis', 223, 9125, 'donec odio justo', 5, 10);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (198, 'Vinegar - Balsamic, White', 234, 8807, 'at nunc commodo placerat', 5, 48);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (199, 'Toothpick Frilled', 232, 3409, 'ultrices phasellus id sapien in', 5, 49);
insert into Productos (id, name, stock, price, info, Categorias_id, Proveedores_id) values (200, 'Pasta - Ravioli', 138, 4441, 'luctus nec molestie', 5, 8);
