insert into Proveedores (id, name, address, phone, info) values (1, 'Fatz', '7646 Longview Park', '1681658855', 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis');
insert into Proveedores (id, name, address, phone, info) values (2, 'Riffpath', '465 Lakeland Alley', '6616224198', 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia');
insert into Proveedores (id, name, address, phone, info) values (3, 'Topicstorm', '9 Alpine Court', '4075446314', 'in felis eu sapien cursus vestibulum proin');
insert into Proveedores (id, name, address, phone, info) values (4, 'Edgeclub', '2739 Alpine Parkway', '4326078649', 'porttitor pede justo eu massa donec dapibus duis');
insert into Proveedores (id, name, address, phone, info) values (5, 'Devshare', '013 Nelson Terrace', '6195436772', 'donec quis orci eget orci vehicula condimentum curabitur');
insert into Proveedores (id, name, address, phone, info) values (6, 'Dazzlesphere', '1 Farmco Hill', '3802978713', 'justo lacinia eget tincidunt eget tempus vel pede');
insert into Proveedores (id, name, address, phone, info) values (7, 'Bubblemix', '47 Rowland Avenue', '2351086917', 'eget vulputate ut ultrices vel augue vestibulum ante');
insert into Proveedores (id, name, address, phone, info) values (8, 'Dabvine', '29890 Knutson Park', '8994928647', 'laoreet ut rhoncus aliquet pulvinar sed nisl');
insert into Proveedores (id, name, address, phone, info) values (9, 'Tazz', '098 Troy Drive', '2411896461', 'augue aliquam erat volutpat in congue etiam justo etiam');
insert into Proveedores (id, name, address, phone, info) values (10, 'Jaxbean', '4083 Valley Edge Pass', '5737708584', 'eget nunc donec quis orci eget orci vehicula condimentum');
insert into Proveedores (id, name, address, phone, info) values (11, 'Zoomdog', '8 Melody Junction', '7526956385', 'aliquet at feugiat non pretium quis lectus suspendisse');
insert into Proveedores (id, name, address, phone, info) values (12, 'Brainbox', '451 Sachtjen Alley', '1672424236', 'sit amet justo morbi ut odio cras mi');
insert into Proveedores (id, name, address, phone, info) values (13, 'Topicware', '11054 Leroy Trail', '4139552505', 'sed sagittis nam congue risus');
insert into Proveedores (id, name, address, phone, info) values (14, 'Yodo', '15 Village Avenue', '8106793393', 'sit amet consectetuer adipiscing elit proin interdum');
insert into Proveedores (id, name, address, phone, info) values (15, 'Abatz', '480 8th Pass', '9744289933', 'luctus et ultrices posuere cubilia curae nulla');
insert into Proveedores (id, name, address, phone, info) values (16, 'Jetwire', '07 Pepper Wood Hill', '2171125275', 'nibh in lectus pellentesque at nulla suspendisse potenti cras');
insert into Proveedores (id, name, address, phone, info) values (17, 'Yakidoo', '2 Carberry Plaza', '2148340097', 'pede ac diam cras pellentesque');
insert into Proveedores (id, name, address, phone, info) values (18, 'Twitterbeat', '3 Petterle Alley', '3529080916', 'nec nisi volutpat eleifend donec ut dolor');
insert into Proveedores (id, name, address, phone, info) values (19, 'Leexo', '5 Almo Trail', '1452843843', 'felis eu sapien cursus vestibulum proin eu');
insert into Proveedores (id, name, address, phone, info) values (20, 'Buzzdog', '23 Talmadge Pass', '7356702666', 'magna bibendum imperdiet nullam orci pede venenatis');
insert into Proveedores (id, name, address, phone, info) values (21, 'Tambee', '7 Buhler Avenue', '6361180235', 'et ultrices posuere cubilia curae donec pharetra magna');
insert into Proveedores (id, name, address, phone, info) values (22, 'Ooba', '8306 Springview Street', '2239567248', 'nullam varius nulla facilisi cras');
insert into Proveedores (id, name, address, phone, info) values (23, 'Skilith', '1673 Alpine Hill', '1059180066', 'eu orci mauris lacinia sapien quis libero');
insert into Proveedores (id, name, address, phone, info) values (24, 'Linkbridge', '45223 Vermont Road', '2768334626', 'rutrum at lorem integer tincidunt ante vel');
insert into Proveedores (id, name, address, phone, info) values (25, 'Zava', '4 Banding Place', '6335128352', 'elementum ligula vehicula consequat morbi a ipsum integer');
insert into Proveedores (id, name, address, phone, info) values (26, 'Dablist', '6563 Boyd Place', '4927978867', 'erat curabitur gravida nisi at nibh in');
insert into Proveedores (id, name, address, phone, info) values (27, 'Vimbo', '35 Chinook Plaza', '2879649022', 'suspendisse potenti cras in purus eu magna');
insert into Proveedores (id, name, address, phone, info) values (28, 'Realpoint', '134 Vidon Lane', '1904690012', 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque');
insert into Proveedores (id, name, address, phone, info) values (29, 'Bubblebox', '1 Marcy Hill', '2451301242', 'donec diam neque vestibulum eget vulputate ut');
insert into Proveedores (id, name, address, phone, info) values (30, 'Twimbo', '3910 Iowa Place', '9095120838', 'felis eu sapien cursus vestibulum');
insert into Proveedores (id, name, address, phone, info) values (31, 'Dynabox', '2650 Rigney Court', '1629154794', 'in consequat ut nulla sed accumsan felis ut at dolor');
insert into Proveedores (id, name, address, phone, info) values (32, 'Npath', '43601 Sugar Way', '5772694586', 'nec nisi vulputate nonummy maecenas tincidunt lacus at');
insert into Proveedores (id, name, address, phone, info) values (33, 'Gigabox', '5 Warner Lane', '2503630981', 'non velit nec nisi vulputate nonummy maecenas tincidunt');
insert into Proveedores (id, name, address, phone, info) values (34, 'Myworks', '2 Upham Terrace', '2527933105', 'ac tellus semper interdum mauris ullamcorper purus sit');
insert into Proveedores (id, name, address, phone, info) values (35, 'Gabtune', '357 Vahlen Crossing', '5823356689', 'quisque ut erat curabitur gravida nisi');
insert into Proveedores (id, name, address, phone, info) values (36, 'Digitube', '826 Summit Place', '3018164815', 'suspendisse potenti nullam porttitor lacus at turpis donec');
insert into Proveedores (id, name, address, phone, info) values (37, 'Zoonoodle', '214 Norway Maple Parkway', '7188131058', 'rutrum neque aenean auctor gravida sem praesent');
insert into Proveedores (id, name, address, phone, info) values (38, 'Zoovu', '83721 Mitchell Drive', '4781482689', 'cursus vestibulum proin eu mi nulla ac enim in');
insert into Proveedores (id, name, address, phone, info) values (39, 'Gevee', '282 Old Shore Lane', '8999334367', 'in imperdiet et commodo vulputate justo in blandit ultrices');
insert into Proveedores (id, name, address, phone, info) values (40, 'Omba', '3 Hazelcrest Park', '7119228762', 'nam ultrices libero non mattis');
insert into Proveedores (id, name, address, phone, info) values (41, 'Brainlounge', '68 East Junction', '2484735971', 'morbi non quam nec dui luctus rutrum nulla tellus');
insert into Proveedores (id, name, address, phone, info) values (42, 'Dynabox', '7 Cherokee Road', '2069559999', 'vehicula consequat morbi a ipsum integer a');
insert into Proveedores (id, name, address, phone, info) values (43, 'Oyoloo', '884 Havey Center', '8153315089', 'morbi non quam nec dui luctus rutrum');
insert into Proveedores (id, name, address, phone, info) values (44, 'Ooba', '7546 Mcguire Pass', '7454687044', 'in lectus pellentesque at nulla suspendisse potenti cras in');
insert into Proveedores (id, name, address, phone, info) values (45, 'Quimba', '328 Eastlawn Circle', '5402955630', 'aliquam sit amet diam in');
insert into Proveedores (id, name, address, phone, info) values (46, 'Skyba', '557 Helena Crossing', '4044532251', 'et ultrices posuere cubilia curae duis');
insert into Proveedores (id, name, address, phone, info) values (47, 'Ntag', '8 East Drive', '4595405230', 'vehicula condimentum curabitur in libero ut massa volutpat');
insert into Proveedores (id, name, address, phone, info) values (48, 'Brainlounge', '55985 Colorado Way', '8871011628', 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc');
insert into Proveedores (id, name, address, phone, info) values (49, 'Yoveo', '32354 Novick Road', '3945604925', 'praesent blandit nam nulla integer pede justo lacinia eget tincidunt');
insert into Proveedores (id, name, address, phone, info) values (50, 'Skynoodle', '6 Hauk Avenue', '6516711097', 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque');
